#!/bin/bash
user=$(whoami)

# install docker-ce
sudo apt install -y ca-certificates curl git
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# install gns3-gui dependencies
sudo apt install -y python3 \
		python3-pip \
		pipx \
		python3-pyqt5 \
		python3-pyqt5.qtwebsockets \
		python3-pyqt5.qtsvg \
		software-properties-common \
		ca-certificates \
		curl \
		gnupg2 \
		wireshark \
		tigervnc-viewer

# install gns3-server dependencies
sudo apt install -y qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips
sudo systemctl enable --now libvirtd
sudo virsh net-autostart default

# install ubridge
sudo apt install -y libpcap-dev
git clone https://github.com/GNS3/ubridge.git /tmp/ubridge
cd /tmp/ubridge
make
sudo make install

# install gns3-gui & gns3-server
pipx ensurepath
pipx install gns3-server
pipx install gns3-gui
pipx inject gns3-gui gns3-server PyQt5

# gns3 create app shortcut
sudo curl -o /usr/share/applications/gns3.desktop https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/applications/gns3.desktop
sudo curl -o /usr/share/mime/packages/gns3-gui.xml https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/gns3-gui.xml
sudo curl -o /usr/share/icons/hicolor/16x16/apps/gns3.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/16x16/apps/gns3.png
sudo curl -o /usr/share/icons/hicolor/32x32/apps/gns3.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/32x32/apps/gns3.png
sudo curl -o /usr/share/icons/hicolor/48x48/apps/gns3.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/48x48/apps/gns3.png
sudo curl -o /usr/share/icons/hicolor/48x48/mimetypes/application-x-gns3.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/48x48/mimetypes/application-x-gns3.png
sudo curl -o /usr/share/icons/hicolor/48x48/mimetypes/application-x-gns3appliance.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/48x48/mimetypes/application-x-gns3appliance.png
sudo curl -o /usr/share/icons/hicolor/48x48/mimetypes/application-x-gns3project.png https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/48x48/mimetypes/application-x-gns3project.png
sudo curl -o /usr/share/icons/hicolor/scalable/apps/gns3.svg https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/scalable/apps/gns3.svg
sudo curl -o /usr/share/icons/hicolor/scalable/apps/application-x-gns3.svg https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/scalable/mimetypes/application-x-gns3.svg
sudo curl -o /usr/share/icons/hicolor/scalable/apps/application-x-gns3appliance.svg https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/scalable/mimetypes/application-x-gns3appliance.svg
sudo curl -o /usr/share/icons/hicolor/scalable/apps/application-x-gns3project.svg https://raw.githubusercontent.com/GNS3/gns3-gui/master/resources/linux/icons/hicolor/scalable/mimetypes/application-x-gns3project.svg
sudo update-icon-caches /usr/share/icons/*

# add user to group permission
sudo usermod -aG docker,wireshark,kvm,libvirt $user
