#!/bin/bash

# INITIAL PACKAGE
sudo pacman -S yakuake gimp libreoffice ktorrent simplescreenrecorder sweeper plasma-systemmonitor ufw plasma-firewall neofetch kcalc htop --noconfirm
yay -S brave-bin zoom viber ttf-ms-fonts sublime-text-4 --noconfirm

# FIREWALL CONFIGURATION
sudo ufw enable
sudo systemctl enable --now ufw

# LAPTOP UTILITIES
if hostnamectl | grep laptop > /dev/null; then
	# bluetooth management
	sudo pacman -S bluedevil --noconfirm
	
	# battery saving utilities
	yay -S tlp tlp-rdw auto-cpufreq --noconfirm
	
	# systemd enable
	sudo systemctl enable --now tlp
	sudo systemctl enable --now auto-cpufreq
	sudo systemctl enable --now bluetooth
	
else echo "Nothing to do"

fi

# SSD OPTIMIZE
if cat /sys/block/sda/queue/rotational | grep 0 > /dev/null; then
	sudo systemctl enable --now fstrim

else echo "Nothing to do"

fi

# PACKAGE MAINTENANCE
yay -Sc --noconfirm
sudo pacman -Sc --noconfirm
sudo pacman -Qtdq | sudo pacman -Rns - --noconfirm