#!/bin/bash

# EDIT THE COUNTRY CODE WITH YOUR LOCATION FOR FASTER MIRROR
sudo reflector --protocol https --latest 10 --sort rate -c CN,HK,TW,SG --save /etc/pacman.d/mirrorlist --verbose

# KDE PACKAGE
sudo pacman -S yakuake gimp libreoffice ktorrent simplescreenrecorder sweeper partitionmanager plasma-systemmonitor ksysguard ufw plasma-firewall neofetch kcalc htop kwallet --noconfirm
yay -S brave-bin zoom viber ttf-ms-fonts sublime-text-4 plasma5-applets-thermal-monitor-git --noconfirm

# GNOME
sudo pacman -S cheese gnome-weather geary pitivi gparted gimp libreoffice simplescreenrecorder ufw neofetch htop gnome-calculator gnome-calendar gnome-photos transmission-gtk bleachbit rhythmbox simple-scan --noconfirm
yay -S brave-bin zoom viber ttf-ms-fonts sublime-text-4 gnome-shell-extension-blur-my-shell-git gnome-shell-extension-system-monitor-git --noconfirm

# SCREEN RECORD BUG FIXED
sudo pacman -Rns xf86-video-intel

# FIREWALL CONFIGURATION
sudo ufw enable
sudo systemctl enable --now ufw

# TIMESHIFT SYSTEM BACKUP AND RESTORE
yay -S grub-btrfs timeshift timeshift-autosnap --noconfirm
sudo systemctl enable --now grub-btrfs

# LAPTOP UTILITIES
if hostnamectl | grep laptop > /dev/null; then
	# bluetooth management
	sudo pacman -S bluedevil --noconfirm
	
	# battery saving utilities
	yay -S tlp tlp-rdw auto-cpufreq --noconfirm
	
	# systemd enable
	sudo systemctl enable --now tlp
	sudo systemctl enable --now auto-cpufreq
	sudo systemctl enable --now bluetooth
	
else echo "Nothing to do"

fi

# SSD OPTIMIZE
if cat /sys/block/sda/queue/rotational | grep 0 > /dev/null; then
	sudo systemctl enable --now fstrim

else echo "Nothing to do"

fi

# PACKAGE MAINTENANCE
yay -Sc --noconfirm
sudo pacman -Sc --noconfirm
sudo pacman -Qtdq | sudo pacman -Rns - --noconfirm
